export const prompts = [
  "A serene mountain landscape during sunset with a lake reflecting the colors of the sky.",
  "A futuristic city skyline with flying cars and neon lights at night.",
  "A magical forest filled with glowing mushrooms and whimsical creatures.",
  "A cozy coffee shop on a rainy day, complete with steaming mugs and bookshelves.",
  "An underwater scene featuring colorful coral reefs and exotic fish swimming by.",
  "A fantasy castle perched on a cliff overlooking a stormy sea.",
  "A bustling street market in a vibrant Asian city, filled with colorful stalls and street food.",
  "A cute animal in a superhero costume, ready to save the day.",
  "A vintage car parked in front of a retro diner, with neon lights glowing at dusk.",
  "A magical library where the books float and the shelves are made of clouds.",
  "An astronaut exploring an alien planet with bizarre landscapes and unusual flora.",
  "A whimsical tea party set in a garden with oversized flowers and talking animals.",
  "A steampunk-inspired airship flying through a cloudy sky, surrounded by gears and gadgets.",
  "A tranquil beach scene with a hammock between two palm trees and a sunset in the background.",
  "A hidden waterfall cascading into a crystal-clear pool surrounded by lush greenery.",
  "A retro robot in a futuristic kitchen, cooking up a delicious meal.",
  "A cozy mountain cabin with smoke coming from the chimney and snow falling outside.",
  "A vibrant carnival scene with colorful rides, games, and excited visitors.",
  "A fairytale-inspired garden with a sparkling fountain and enchanting creatures.",
  "A mystical dragon soaring through a starry night sky with a full moon.",
];
