import React, { useState } from "react";
import { Card, FormField, Loader } from "../components";

const RenderCards = ({ data, title }) => {
  if (data.legth > 0) {
    return data.map((post) => {
      <Card key={post?.id} {...post} />;
    });
  }
  return <h2>{title}</h2>;
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState("");
  return (
    <section className="max-w-7xl mx-auto">
      <div className="text-center">
        {" "}
        <h1 className="font-extrabold text-[35px]">Community Showcase</h1>
        <p className="mt-3 text-gray-400 text-[18px] max-w-[700px] mx-auto">
          {" "}
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-20">Form Field</div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            {" "}
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="">
                Showing Results for{" "}
                <span className="text-red-500 font-bold">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No Posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
